### ISSUE TITLE
bug connection refused

### ISSUE THREAD

**Issue by unijad** [zidsa/zid-theme-npm#17]
**Description**
I cannot connect to my account nor to do any other funcitionaly caused by `ECONNREFUSED` error

**Steps to Reproduce**
2. Fresh Install CLI using `yarn global add @zidsa/themes-cli`
3. create new theme `themes-cli new my-awesome-theme `
4. attempt to login `themes-cli login`
5- attempt to preview using `themes-cli preview --store_email gjtd0m6tfh@zam-partner.email`

**Expected Behavior**
1- to be able to login
2- to be able to preview theme

**Actual Behavior**
1- fail to login doe to callback to localhost from browser CROSS origin blocked network call
2- fail to connect 

**Logs**
```
 my-awesome-theme themes-cli preview --store_email gjtd0m6tfh@zam-partner.email
undefined  preview command called with store_email:
Unexpected error during API call: fe [AggregateError]
    at fe.from (/Users/younis/.config/yarn/global/node_modules/@zidsa/themes-cli/dist/zid-theme.js:2:281072)
    at y.<anonymous> (/Users/younis/.config/yarn/global/node_modules/@zidsa/themes-cli/dist/zid-theme.js:2:303520)
    at y.emit (node:events:519:35)
    at d.forEach.f.<computed> (/Users/younis/.config/yarn/global/node_modules/@zidsa/themes-cli/dist/zid-theme.js:2:105644)
    at ClientRequest.emit (node:events:507:28)
    at emitErrorEvent (node:_http_client:103:11)
    at Socket.socketErrorListener (node:_http_client:506:5)
    at Socket.emit (node:events:507:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at an.request (/Users/younis/.config/yarn/global/node_modules/@zidsa/themes-cli/dist/zid-theme.js:2:315599)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  code: 'ECONNREFUSED',
  errors: [
    Error: connect ECONNREFUSED ::1:9090
        at createConnectionError (node:net:1656:14)
        at afterConnectMultiple (node:net:1686:16) {
      errno: -61,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 9090
    },
    Error: connect ECONNREFUSED 127.0.0.1:9090
        at createConnectionError (node:net:1656:14)
        at afterConnectMultiple (node:net:1686:16) {
      errno: -61,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 9090
    }
  ],
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function (anonymous)] ],
    transformResponse: [ [Function (anonymous)] ],
    timeout: 500000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
      'x-partner-token': 'eyJpdiI6InhPVE1JMWluMlRDQVhtVVpaTVJrRkE9PSIsInZhbHVlIjoia1BhOWlaMkluTWlmV2drOGtDeUJCL2hoUDNlZkQxZk5FVUpMQ1M0a1k4NVljNFZJbEhKZm1LbDhtZmRZQXVmWFQvNW1PaGtqMW1Qd1R6TjluZDJDTG52YlovTXF2VXNIelIwclpobVh2WHZoT0lnSTN4NkJGOWZjeDJUTmdNejRROWdkdnQ3YXpOV2JYY2V6NnZiMDJjQkMxb2VndHp5SHlyTm9xZXAxeit2UFFNaDFpdjNMUUpIaHZMRnZjYXdzVjBaR3o0dnc5NXEvd21rZlhNT1RPZz09IiwibWFjIjoiMDRiNzIyNzhiZWJiMzZlOTRhN2I1ZTg5MDFkYzQ0ZDQ5Nzg2OWQxNjhiNDgzNmRmZmI3NTI5YmU2M2IxYTEzZiIsInRhZyI6IiJ9',
      'User-Agent': 'axios/1.7.3',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    url: 'http://localhost:9090/v1/market/dev-stores',
    method: 'get',
    data: undefined
  },
  request: <ref *1> Writable {
    _events: {
      close: undefined,
      error: [Function (anonymous)],
      prefinish: undefined,
      finish: undefined,
      drain: undefined,
      response: [Function (anonymous)],
      socket: [Array],
      timeout: undefined,
      abort: undefined
    },
    _writableState: WritableState {
      highWaterMark: 65536,
      length: 0,
      corked: 0,
      onwrite: [Function: bound onwrite],
      writelen: 0,
      bufferedIndex: 0,
      pendingcb: 0,
      [Symbol(kState)]: 17580812,
      [Symbol(kBufferedValue)]: null
    },
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/v1/market/dev-stores',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: _t],
      beforeRedirects: [Object],
      hostname: 'localhost',
      port: '9090',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/v1/market/dev-stores'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _eventsCount: 3,
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      _header: 'GET /v1/market/dev-stores HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'x-partner-token: eyJpdiI6InhPVE1JMWluMlRDQVhtVVpaTVJrRkE9PSIsInZhbHVlIjoia1BhOWlaMkluTWlmV2drOGtDeUJCL2hoUDNlZkQxZk5FVUpMQ1M0a1k4NVljNFZJbEhKZm1LbDhtZmRZQXVmWFQvNW1PaGtqMW1Qd1R6TjluZDJDTG52YlovTXF2VXNIelIwclpobVh2WHZoT0lnSTN4NkJGOWZjeDJUTmdNejRROWdkdnQ3YXpOV2JYY2V6NnZiMDJjQkMxb2VndHp5SHlyTm9xZXAxeit2UFFNaDFpdjNMUUpIaHZMRnZjYXdzVjBaR3o0dnc5NXEvd21rZlhNT1RPZz09IiwibWFjIjoiMDRiNzIyNzhiZWJiMzZlOTRhN2I1ZTg5MDFkYzQ0ZDQ5Nzg2OWQxNjhiNDgzNmRmZmI3NTI5YmU2M2IxYTEzZiIsInRhZyI6IiJ9\r\n' +
        'User-Agent: axios/1.7.3\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: localhost:9090\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/v1/market/dev-stores',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kChunkedBuffer)]: [],
      [Symbol(kChunkedLength)]: 0,
      [Symbol(kSocket)]: [Socket],
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 65536,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://localhost:9090/v1/market/dev-stores',
    _timeout: null,
    [Symbol(shapeMode)]: true,
    [Symbol(kCapture)]: false
  },
  cause: AggregateError [ECONNREFUSED]: 
      at internalConnectMultiple (node:net:1128:18)
      at afterConnectMultiple (node:net:1693:7) {
    code: 'ECONNREFUSED',
    [errors]: [ [Error], [Error] ]
  }
}
error fe [AggregateError]
    at fe.from (/Users/younis/.config/yarn/global/node_modules/@zidsa/themes-cli/dist/zid-theme.js:2:281072)
    at y.<anonymous> (/Users/younis/.config/yarn/global/node_modules/@zidsa/themes-cli/dist/zid-theme.js:2:303520)
    at y.emit (node:events:519:35)
    at d.forEach.f.<computed> (/Users/younis/.config/yarn/global/node_modules/@zidsa/themes-cli/dist/zid-theme.js:2:105644)
    at ClientRequest.emit (node:events:507:28)
    at emitErrorEvent (node:_http_client:103:11)
    at Socket.socketErrorListener (node:_http_client:506:5)
    at Socket.emit (node:events:507:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at an.request (/Users/younis/.config/yarn/global/node_modules/@zidsa/themes-cli/dist/zid-theme.js:2:315599)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  code: 'ECONNREFUSED',
  errors: [
    Error: connect ECONNREFUSED ::1:9090
        at createConnectionError (node:net:1656:14)
        at afterConnectMultiple (node:net:1686:16) {
      errno: -61,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 9090
    },
    Error: connect ECONNREFUSED 127.0.0.1:9090
        at createConnectionError (node:net:1656:14)
        at afterConnectMultiple (node:net:1686:16) {
      errno: -61,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 9090
    }
  ],
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function (anonymous)] ],
    transformResponse: [ [Function (anonymous)] ],
    timeout: 500000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
      'x-partner-token': 'eyJpdiI6InhPVE1JMWluMlRDQVhtVVpaTVJrRkE9PSIsInZhbHVlIjoia1BhOWlaMkluTWlmV2drOGtDeUJCL2hoUDNlZkQxZk5FVUpMQ1M0a1k4NVljNFZJbEhKZm1LbDhtZmRZQXVmWFQvNW1PaGtqMW1Qd1R6TjluZDJDTG52YlovTXF2VXNIelIwclpobVh2WHZoT0lnSTN4NkJGOWZjeDJUTmdNejRROWdkdnQ3YXpOV2JYY2V6NnZiMDJjQkMxb2VndHp5SHlyTm9xZXAxeit2UFFNaDFpdjNMUUpIaHZMRnZjYXdzVjBaR3o0dnc5NXEvd21rZlhNT1RPZz09IiwibWFjIjoiMDRiNzIyNzhiZWJiMzZlOTRhN2I1ZTg5MDFkYzQ0ZDQ5Nzg2OWQxNjhiNDgzNmRmZmI3NTI5YmU2M2IxYTEzZiIsInRhZyI6IiJ9',
      'User-Agent': 'axios/1.7.3',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    url: 'http://localhost:9090/v1/market/dev-stores',
    method: 'get',
    data: undefined
  },
  request: <ref *1> Writable {
    _events: {
      close: undefined,
      error: [Function (anonymous)],
      prefinish: undefined,
      finish: undefined,
      drain: undefined,
      response: [Function (anonymous)],
      socket: [Array],
      timeout: undefined,
      abort: undefined
    },
    _writableState: WritableState {
      highWaterMark: 65536,
      length: 0,
      corked: 0,
      onwrite: [Function: bound onwrite],
      writelen: 0,
      bufferedIndex: 0,
      pendingcb: 0,
      [Symbol(kState)]: 17580812,
      [Symbol(kBufferedValue)]: null
    },
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/v1/market/dev-stores',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: _t],
      beforeRedirects: [Object],
      hostname: 'localhost',
      port: '9090',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/v1/market/dev-stores'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _eventsCount: 3,
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      _header: 'GET /v1/market/dev-stores HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'x-partner-token: eyJpdiI6InhPVE1JMWluMlRDQVhtVVpaTVJrRkE9PSIsInZhbHVlIjoia1BhOWlaMkluTWlmV2drOGtDeUJCL2hoUDNlZkQxZk5FVUpMQ1M0a1k4NVljNFZJbEhKZm1LbDhtZmRZQXVmWFQvNW1PaGtqMW1Qd1R6TjluZDJDTG52YlovTXF2VXNIelIwclpobVh2WHZoT0lnSTN4NkJGOWZjeDJUTmdNejRROWdkdnQ3YXpOV2JYY2V6NnZiMDJjQkMxb2VndHp5SHlyTm9xZXAxeit2UFFNaDFpdjNMUUpIaHZMRnZjYXdzVjBaR3o0dnc5NXEvd21rZlhNT1RPZz09IiwibWFjIjoiMDRiNzIyNzhiZWJiMzZlOTRhN2I1ZTg5MDFkYzQ0ZDQ5Nzg2OWQxNjhiNDgzNmRmZmI3NTI5YmU2M2IxYTEzZiIsInRhZyI6IiJ9\r\n' +
        'User-Agent: axios/1.7.3\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: localhost:9090\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/v1/market/dev-stores',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kChunkedBuffer)]: [],
      [Symbol(kChunkedLength)]: 0,
      [Symbol(kSocket)]: [Socket],
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 65536,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://localhost:9090/v1/market/dev-stores',
    _timeout: null,
    [Symbol(shapeMode)]: true,
    [Symbol(kCapture)]: false
  },
  cause: AggregateError [ECONNREFUSED]: 
      at internalConnectMultiple (node:net:1128:18)
      at afterConnectMultiple (node:net:1693:7) {
    code: 'ECONNREFUSED',
    [errors]: [ [Error], [Error] ]
  }
}
```

**Comment by unijad** [comment]
looks like unmaintained repo/project

**Comment by AntonVasylchenko** [comment]
I have the same problems

**Comment by youssef-jad** [comment]
Hey Champs,
Thanks for sharing this Trace 

as for Login part this need to be done first so by running 
`themes-cli login`

if port 4444 not used at your end and everything is good in term of NodeJs Version and NPM " isuggest you use NPM" 
you should be having this response 

![image](https://github.com/user-attachments/assets/490cb588-b695-4721-a956-03f418e10d61)

then you can go to the following URL : https://partner.zid.sa/cli/authorized in case it didnt trigger automatically for you 

the given URL will make an API call to your localhost 
`http://localhost:4444/auth/callback?token=`

you can find it via inspect ->. network 
if you encounter CROS issue for any reason you can open that link in new tab and should trigger on your localhost directly 

![image](https://github.com/user-attachments/assets/b3118faf-f324-45a1-852c-31c66d34d139)

then you should be able to work without any issues in upcoming requests

**Comment by AntonVasylchenko** [comment]
I don't understand how this can help me to run the project via cli, since I use NPM instead of Yarn, and I am still having the error.

https://www.loom.com/share/6a7599cfb8a0406d9a0b1ae97ca0e8f8?sid=c33bf6da-921b-41df-a12a-c2e1f2357954

What am I doing wrong?

**Comment by AntonVasylchenko** [comment]
Thank you very much.

**Comment by AntonVasylchenko** [comment]
@unijad Is there any information on when the CLI will be ready?

**Comment by dawnbirth** [comment]
@unijad Correct, the build was made using the local env URL instead. Will fix this soon. 🙏
