### ISSUE TITLE
throw new ERR_INVALID_FILE_URL_PATH('must be absolute')

### ISSUE THREAD

**Issue by saraElsanan** [zidsa/zid-theme-npm#18]
I installed the new Cli 
and then i tried to creat a new theme or even login or using the help , i always get this error  
**PS. We use NVM to mange multiple Node versions , so i tested on v14 , v16 , v18 , v20 and still the same issue in every vesrion 
plusI tested on 4 different machines and i still have the same issue** 

any help please 

```
 themes-cli new my-awesome-theme 
node:internal/url:1450
    throw new ERR_INVALID_FILE_URL_PATH('must be absolute');
    ^

TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute
    at new NodeError (node:internal/errors:405:5)
    at getPathFromURLWin32 (node:internal/url:1450:11)
    at fileURLToPath (node:internal/url:1480:22)
    at 9553 (C:\Users\Sara\AppData\Roaming\nvm\v18.20.3\node_modules\@zidsa\themes-cli\dist\zid-theme.js:2:322609)
    at a (C:\Users\Sara\AppData\Roaming\nvm\v18.20.3\node_modules\@zidsa\themes-cli\dist\zid-theme.js:2:597286)
    at 6970 (C:\Users\Sara\AppData\Roaming\nvm\v18.20.3\node_modules\@zidsa\themes-cli\dist\zid-theme.js:2:264511)
    at a (C:\Users\Sara\AppData\Roaming\nvm\v18.20.3\node_modules\@zidsa\themes-cli\dist\zid-theme.js:2:597286)
    at 7933 (C:\Users\Sara\AppData\Roaming\nvm\v18.20.3\node_modules\@zidsa\themes-cli\dist\zid-theme.js:2:261630)
    at a (C:\Users\Sara\AppData\Roaming\nvm\v18.20.3\node_modules\@zidsa\themes-cli\dist\zid-theme.js:2:597286)
    at 8186 (C:\Users\Sara\AppData\Roaming\nvm\v18.20.3\node_modules\@zidsa\themes-cli\dist\zid-theme.js:2:246224) {
  code: 'ERR_INVALID_FILE_URL_PATH'
}

Node.js v18.20.3
```

**Comment by saraElsanan** [comment]
is there any update in this issue ?

**Comment by anas-js** [comment]
i have same error

**Comment by pdj1985** [comment]
Hello @anas-js and @saraElsanan i'm testing the fix, should be released shortly

**Comment by anas-js** [comment]
The problem is not solved @pdj1985 

![Image](https://github.com/user-attachments/assets/97ccedf4-de20-430f-a59a-12620e5868a1)

**Comment by pdj1985** [comment]
Hello @anas-js did you build the latest version of the client? I tested it both Mac and windows 10 and worked fine. Could you provide more info?

**Comment by anas-js** [comment]
> Hello [@anas-js](https://github.com/anas-js) did you build the latest version of the client? I tested it both Mac and windows 10 and worked fine. Could you provide more info?

@pdj1985 

I deleted the package and re-downloaded it as shown in front of you. For more information:
- windows 11
- npm 11.0.0
- node  v22.11.0

**Comment by SaraMohElsanan** [comment]
i still have the same issue , I uninstalled the old version and reinstall it
ans i still get the same error 
this is the version of the package
 "@zidsa/themes-cli": {
      "version": "1.0.5",
      "overridden": false
    },

i'm using windows 11 
node 18.12.1
npm 8.19.2

`> themes-cli help
node:internal/url:1458
    throw new ERR_INVALID_FILE_URL_PATH('must be absolute');
    ^

TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute
    at new NodeError (node:internal/errors:393:5)
    at getPathFromURLWin32 (node:internal/url:1458:11)
    at fileURLToPath (node:internal/url:1488:22)
    at 9553 (C:\Users\sosys\AppData\Roaming\npm\node_modules\@zidsa\themes-cli\dist\zid-theme.js:2:327720)
    at a (C:\Users\sosys\AppData\Roaming\npm\node_modules\@zidsa\themes-cli\dist\zid-theme.js:2:602880)
    at 6970 (C:\Users\sosys\AppData\Roaming\npm\node_modules\@zidsa\themes-cli\dist\zid-theme.js:2:269694)
    at a (C:\Users\sosys\AppData\Roaming\npm\node_modules\@zidsa\themes-cli\dist\zid-theme.js:2:602880)
    at 7933 (C:\Users\sosys\AppData\Roaming\npm\node_modules\@zidsa\themes-cli\dist\zid-theme.js:2:265939)
    at a (C:\Users\sosys\AppData\Roaming\npm\node_modules\@zidsa\themes-cli\dist\zid-theme.js:2:602880)
    at 8186 (C:\Users\sosys\AppData\Roaming\npm\node_modules\@zidsa\themes-cli\dist\zid-theme.js:2:246224) {
  code: 'ERR_INVALID_FILE_URL_PATH'
}`

**Comment by pdj1985** [comment]
I will double check it tomorrow, thanks for reporting it.

**Comment by anas-js** [comment]
@pdj1985  any Updates?

**Comment by pdj1985** [comment]
Hello @anas-js i tried to reproduct it to no avail, please check my[video](https://jam.dev/c/591990e3-4d3f-4c6f-a37e-f6e2b9923f4a). Let me know if we can have a call and check it sharing your screen

**Comment by pdj1985** [comment]
For some reason, the audio is not heard, but basically i was saying I couldn't reproduce it in windows 11 nor 10, so im not sure how else i can try it.

**Comment by SaraMohElsanan** [comment]
we found the issue and we fixed it , I need to contact you in messages or email , to show you the error and why it only appears with us and not to you

**Comment by pdj1985** [comment]
Hello @SaraMohElsanan sure, juan.martinez@zid.sa, feel free to reach anytime.

**Comment by mo-abdelazem** [comment]
> we found the issue and we fixed it , I need to contact you in messages or email , to show you the error and why it only appears with us and not to you

can you please share the soultion with me 404amed@gmail.com
